import json

import spacy

# from blackstone.displacy_palette import ner_displacy_options
# from spacy import displacy
from blackstone.pipeline.compound_cases import CompoundCases
from blackstone.utils.legislation_linker import extract_legislation_relations

# Load the model
nlp = spacy.load("en_blackstone_proto")

compound_pipe = CompoundCases(nlp)
nlp.add_pipe(compound_pipe)


def get_top_cat(doc):
    """
    Function to identify the highest scoring category
    prediction generated by the text categoriser.
    """
    cats = doc.cats
    max_score = max(cats.values())
    max_cats = [k for k, v in cats.items() if v == max_score]
    max_cat = max_cats[0]
    return (max_cat, max_score)


f = open("judgement/judgements.json", "r")

judgements = json.load(f)

f.close()

for key in judgements.keys():
    for k, v in judgements[key].items():
        print(f"{k}: ")
        text = "\n".join(v)
        doc = nlp(text)

        """Sentence segmenting and applying the text categoriser model"""
        for sentence in doc.sents:
            if sentence.text.strip() != "":
                doc = nlp(sentence.text)
                top_category = get_top_cat(doc)
                print(f'"{sentence.text}" {top_category}\n')

        """Applying the NER model and visualising entities"""
        for ent in doc.ents:
            print(f"{ent.label_}: {ent.text}")
            # displacy.serve(doc, style="ent", options=ner_displacy_options)

        """Compound case reference detection"""
        for compound_ref in doc._.compound_cases:
            print(compound_ref)

        """Legislation linker"""
        relations = extract_legislation_relations(doc)
        for provision, provision_url, instrument, instrument_url in relations:
            print(f"\n{provision}\t{provision_url}\t{instrument}\t{instrument_url}")
